---
- name: Install Mysql repository
  yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm state=present

- name: delete mariadb
  yum:
    name: mariadb-libs
    state: removed

- name: amazon-axtraを使ってphp8.0をinstallします.
  shell: "amazon-linux-extras install -y php8.0"
  become: yes

- name: install yum packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    lock_timeout: 300
  with_items: '{{ yum_packages }}'
- name: Download and unarchive wordpress file
  unarchive:
    src: '{{ archive_url }}'
    dest: '{{ install_path }}'
    remote_src: yes
- name: Create symbolic-link for apache
  file:
    src: '{{ install_path }}/wordpress'
    dest: /var/www/html/wordpress
    state: link

- name: Change file ownership for apache
  file:
    path: '{{ install_path }}/wordpress'
    owner: apache
    group: apache
    recurse: yes
- name: Start services
  service:
    name: '{{ item.name }}'
    enabled: '{{ item.enabled | default("yes") }}'
    state: '{{ item.state | default("started") }}'
  with_items:
    - name: httpd
    - name: mysqld
- name: get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: root_password
- name: update expired root user password
  command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root.password }}';"
- name: copy my.cnf
  copy:
    src: ../files/etc/my.cnf
    dest: /etc/my.cnf
    mode: 0644
- name: copy .my.cnf
  copy:
    src: ../files/etc/.my.cnf
    dest: /root/.my.cnf
    mode: 0644
- name: enable mysql
  systemd:
    name: mysqld
    state: restarted
    enabled: yes
- name: mysqlの認証方法を変更
  command: mysql --user root --password={{ mysql.root.password }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql.root.password }}';"
- name: create mysql client user
  mysql_user:
    login_user: root
    login_password: "{{ mysql.root.password }}"
    name: "{{ mysql_user.name }}"
    password: "{{ mysql_user.password }}"
    priv: '*.*:ALL,GRANT'
    state: present

- name: Create database for wordpress
  mysql_db:
    name: '{{ mysql_db.db_name }}'
    state: present